language: python
python:
- '3.7'
os: linux
before_install:
- openssl aes-256-cbc -K $encrypted_40eddaed022c_key -iv $encrypted_40eddaed022c_iv -in account.session.enc -out test/account.session -d
- openssl aes-256-cbc -K $encrypted_40eddaed022c_key -iv $encrypted_40eddaed022c_iv  -in config.ini.enc -out test/config.ini -d
install:
- pip install requirements.txt
- pip install ./test/requirements.txt
script:
- python run.py
- cd test && pytest
