language: python
python:
- '3.7-dev'
os: linux
before_install:
- openssl aes-256-cbc -K $encrypted_40eddaed022c_key -iv $encrypted_40eddaed022c_iv -in account.session.enc -out test/account.session -d
- openssl aes-256-cbc -K $encrypted_40eddaed022c_key -iv $encrypted_40eddaed022c_iv  -in config.ini.enc -out test/config.ini -d
install:
- pip install requirements.txt
- pip3 install --upgrade  git+https://github.com/blue-bird1/tgintegration
script:
- python run.py
- cd test && pytest
