language: python
python:
- 3.7-dev
os: linux
before_install:
- openssl aes-256-cbc -K $encrypted_40eddaed022c_key -iv $encrypted_40eddaed022c_iv -in account.session.enc -out test/account.session -d
install:
- pip install -r requirements.txt
- sudo pip install  git+https://github.com/blue-bird1/tgintegration
script:
- python run.py
- cd test && pytest
